In [115]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, BaggingClassifier, AdaBoostClassifier
from mlxtend.classifier import StackingClassifier

In [44]:
filename = 'https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter15/Dataset/crx.data '
credData = pd.read_csv(filename, sep= ",", header = None, na_values = "? ")
credData.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [45]:
# O segundo parâmetro fala para modificar apenas a coluna 15
credData.loc[credData[15] == '+', 15] = 1
credData.loc[credData[15] == '-', 15] = 0

In [47]:
credData.sample(15)

0      1       2  3  4   5  6      7  8  9   10 11 12     13     14 15
658  a  15.75   0.375  u  g   c  v  1.000  f  f   0  f  g  00120     18  0
163  b  32.00   1.750  y  p   e  h  0.040  t  f   0  t  g  00393      0  1
416  b  22.50   0.125  y  p   k  v  0.125  f  f   0  f  g  00200     70  0
338  a  33.25   3.000  y  p  aa  v  2.000  f  f   0  f  g  00180      0  0
66   a  36.00   1.000  u  g   c  v  2.000  t  t  11  f  g  00000    456  1
235  a  20.67   1.835  u  g   q  v  2.085  t  t   5  f  g  00220   2503  1
508  a  30.67  12.000  u  g   c  v  2.000  t  t   1  f  g  00220     19  1
6    b  33.17   1.040  u  g   r  h  6.500  t  f   0  t  g  00164  31285  1
645  b  37.33   2.665  u  g  cc  v  0.165  f  f   0  t  g  00000    501  0
7    a  22.92  11.585  u  g  cc  v  0.040  t  f   0  f  g  00080   1349  1
301  b  18.25   0.165  u  g   d  v  0.250  f  f   0  t  s  00280      0  0
473  b  19.17   4.000  y  p   i  v  1.000  f  f   0  t  g  00360   1000  0
220  a  50.08  12.540  u  g  aa  v  2.290  t  t   3  t  g  00156      0  1
346  ?  32.25   1.500  u  g   c  v  0.250  f  f   0  t  g  00372    122  0
539  b  80.25   5.500  u  g   ?  ?  0.540  t  f   0  f  g  00000    340  0

In [48]:
credData = credData.replace('?', np.nan)

In [49]:
credData.sample(20)

0      1       2  3  4    5    6      7  8  9   10 11 12     13    14  \
537    b  35.25   3.165  u  g    x    h  3.750  t  f   0  t  g  00680     0   
139    a  26.92  13.500  u  g    q    h  5.000  t  t   2  f  g  00000  5000   
500    b    NaN   4.000  u  g    x    v  5.000  t  t   3  t  g  00290  2279   
479  NaN  26.50   2.710  y  p  NaN  NaN  0.085  f  f   0  f  s  00080     0   
376    b  28.67  14.500  u  g    d    v  0.125  f  f   0  f  g  00000   286   
589    b  25.33   0.580  u  g    c    v  0.290  t  t   7  t  g  00096  5124   
50     a  25.75   0.500  u  g    c    h  0.875  t  f   0  t  g  00491     0   
526    b  41.58   1.750  u  g    k    v  0.210  t  f   0  f  g  00160     0   
560    a  25.00  12.330  u  g   cc    h  3.500  t  t   6  f  g  00400   458   
643    a  52.50   7.000  u  g   aa    h  3.000  f  f   0  f  g  00000     0   
141    a  56.50  16.000  u  g    j   ff  0.000  t  t  15  f  g  00000   247   
305    b  48.75  26.335  y  p   ff   ff  0.000  t  f   0  t  g  00000     0   
515    b    NaN  10.500  u  g    x    v  6.500  t  f   0  f  g  00000     0   
482    a  17.33   9.500  u  g   aa    v  1.750  f  t  10  t  g  00000    10   
664    b  31.08   1.500  y  p    w    v  0.040  f  f   0  f  s  00160     0   
166    b  19.33   9.500  u  g    q    v  1.000  t  f   0  t  g  00060   400   
568    b  43.08   0.375  y  p    c    v  0.375  t  t   8  t  g  00300   162   
404    b  34.00   5.085  y  p    i   bb  1.085  f  f   0  t  g  00480     0   
625    b  23.75  12.000  u  g    c    v  2.085  f  f   0  f  s  00080     0   
21     b  23.25   1.000  u  g    c    v  0.835  t  f   0  f  s  00300     0   

     15  
537   0  
139   1  
500   1  
479   0  
376   0  
589   1  
50    1  
526   0  
560   1  
643   0  
141   1  
305   0  
515   1  
482   0  
664   0  
166   1  
568   1  
404   0  
625   0  
21    1

In [50]:
credData.isna().sum()

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

In [51]:
credData.dtypes

0      object
1      object
2     float64
3      object
4      object
5      object
6      object
7     float64
8      object
9      object
10      int64
11     object
12     object
13     object
14      int64
15      int64
dtype: object

In [52]:
credData.shape

(690, 16)

In [53]:
newCred = credData.dropna(0)
newCred.shape

(653, 16)

In [54]:
credCat = pd.get_dummies(newCred[[0, 3, 4, 5, 6, 8, 9, 11, 12]])

In [55]:
credNum = newCred[[1, 2, 7, 10, 13, 14]]

In [56]:
X = pd.concat([credCat, credNum], 1)
y = newCred[15]

In [57]:
scaler = MinMaxScaler()
X_tran = pd.DataFrame(scaler.fit_transform(X))

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X_tran, y, test_size=0.3, random_state=123)

In [61]:
model = LogisticRegression()

In [62]:
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [63]:
preds = model.predict(X_test)

In [65]:
print(confusion_matrix(y_test, preds))
print('\n', classification_report(y_test, preds))

[[93 14]
 [ 8 81]]

               precision    recall  f1-score   support

           0       0.92      0.87      0.89       107
           1       0.85      0.91      0.88        89

    accuracy                           0.89       196
   macro avg       0.89      0.89      0.89       196
weighted avg       0.89      0.89      0.89       196



### Averaging Technique

In [68]:
filename = 'https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter15/Dataset/crx.data '
credData = pd.read_csv(filename, sep= ",", header = None, na_values = "? ")
credData.head()

# O segundo parâmetro fala para modificar apenas a coluna 15
credData.loc[credData[15] == '+', 15] = 1
credData.loc[credData[15] == '-', 15] = 0

credData = credData.replace('?', np.nan)

newCred = credData.dropna(0)

credCat = pd.get_dummies(newCred[[0, 3, 4, 5, 6, 8, 9, 11, 12]])

credNum = newCred[[1, 2, 7, 10, 13, 14]]

X = pd.concat([credCat, credNum], 1)
y = newCred[15]

scaler = MinMaxScaler()
X_tran = pd.DataFrame(scaler.fit_transform(X))

X_train, X_test, y_train, y_test = train_test_split(X_tran, y, test_size=0.3, random_state=123)

In [69]:
model1 = LogisticRegression(random_state=123)
model2 = KNeighborsClassifier(n_neighbors=5)
model3 = RandomForestClassifier(n_estimators=500)

In [70]:
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [72]:
preds1 = model1.predict_proba(X_test)
preds2 = model2.predict_proba(X_test)
preds3 = model3.predict_proba(X_test)

In [73]:
emsemblePreds = (preds1 + preds2 + preds3) / 3

In [74]:
emsemblePreds[0:4, :]

array([[0.89983583, 0.10016417],
       [0.96196145, 0.03803855],
       [0.1802414 , 0.8197586 ],
       [0.05416821, 0.94583179]])

In [75]:
print(model1.classes_)
print(model2.classes_)
print(model3.classes_)

[0 1]
[0 1]
[0 1]


In [76]:
# O argumento máximo dita a maior probabilidade no eixo 1 das previsoes
preds = np.argmax(emsemblePreds, axis=1)
preds

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1],
      dtype=int64)

In [78]:
print(confusion_matrix(y_test, preds))

[[95 12]
 [ 8 81]]


In [80]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.92      0.89      0.90       107
           1       0.87      0.91      0.89        89

    accuracy                           0.90       196
   macro avg       0.90      0.90      0.90       196
weighted avg       0.90      0.90      0.90       196



## Weighted Averaging Technique

In [81]:
filename = 'https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter15/Dataset/crx.data '
credData = pd.read_csv(filename, sep= ",", header = None, na_values = "? ")
credData.head()

# O segundo parâmetro fala para modificar apenas a coluna 15
credData.loc[credData[15] == '+', 15] = 1
credData.loc[credData[15] == '-', 15] = 0

credData = credData.replace('?', np.nan)

newCred = credData.dropna(0)

credCat = pd.get_dummies(newCred[[0, 3, 4, 5, 6, 8, 9, 11, 12]])

credNum = newCred[[1, 2, 7, 10, 13, 14]]

X = pd.concat([credCat, credNum], 1)
y = newCred[15]

scaler = MinMaxScaler()
X_tran = pd.DataFrame(scaler.fit_transform(X))

X_train, X_test, y_train, y_test = train_test_split(X_tran, y, test_size=0.3, random_state=123)

model1 = LogisticRegression(random_state=123)
model2 = KNeighborsClassifier(n_neighbors=5)
model3 = RandomForestClassifier(n_estimators=500)

model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

preds1 = model1.predict_proba(X_test)
preds2 = model2.predict_proba(X_test)
preds3 = model3.predict_proba(X_test)

In [82]:
# A soma dos pesos tem que dar 1
ensemblePreds = ((preds1 * 0.60) + (preds2 + 0.20) + (preds3 + 0.20))

In [83]:
preds = np.argmax(ensemblePreds, axis=1)

In [84]:
print(confusion_matrix(y_test, preds))

[[97 10]
 [ 8 81]]


In [85]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.92      0.91      0.92       107
           1       0.89      0.91      0.90        89

    accuracy                           0.91       196
   macro avg       0.91      0.91      0.91       196
weighted avg       0.91      0.91      0.91       196



## Max Voting

In [86]:
filename = 'https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter15/Dataset/crx.data '
credData = pd.read_csv(filename, sep= ",", header = None, na_values = "? ")
credData.head()

# O segundo parâmetro fala para modificar apenas a coluna 15
credData.loc[credData[15] == '+', 15] = 1
credData.loc[credData[15] == '-', 15] = 0

credData = credData.replace('?', np.nan)

newCred = credData.dropna(0)

credCat = pd.get_dummies(newCred[[0, 3, 4, 5, 6, 8, 9, 11, 12]])

credNum = newCred[[1, 2, 7, 10, 13, 14]]

X = pd.concat([credCat, credNum], 1)
y = newCred[15]

scaler = MinMaxScaler()
X_tran = pd.DataFrame(scaler.fit_transform(X))

X_train, X_test, y_train, y_test = train_test_split(X_tran, y, test_size=0.3, random_state=123)

In [87]:
model1 = LogisticRegression(random_state=123)
model2 = KNeighborsClassifier(n_neighbors=5)
model3 = RandomForestClassifier(n_estimators=500)

In [90]:
# voting = 'hard' significa que o modelo retorna uma classe e não uma probabilidade
model = VotingClassifier(estimators=[('lr', model1), ('knn', model2), ('rf', model3)], voting='hard')

In [91]:
model.fit(X_train, y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=123,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('knn',
                              KNeighborsClassifier(algorithm='auto',
                                                   leaf_size=30,
                                                   metric='minkowski',
                                                 

In [92]:
model.score(X_test, y_test)

0.9030612244897959

In [93]:
preds = model.predict(X_test)

In [94]:
print(confusion_matrix(y_test, preds))

[[95 12]
 [ 7 82]]


In [95]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.93      0.89      0.91       107
           1       0.87      0.92      0.90        89

    accuracy                           0.90       196
   macro avg       0.90      0.90      0.90       196
weighted avg       0.90      0.90      0.90       196



## Bagging

In [96]:
filename = 'https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter15/Dataset/crx.data '
credData = pd.read_csv(filename, sep= ",", header = None, na_values = "? ")
credData.head()

# O segundo parâmetro fala para modificar apenas a coluna 15
credData.loc[credData[15] == '+', 15] = 1
credData.loc[credData[15] == '-', 15] = 0

credData = credData.replace('?', np.nan)

newCred = credData.dropna(0)

credCat = pd.get_dummies(newCred[[0, 3, 4, 5, 6, 8, 9, 11, 12]])

credNum = newCred[[1, 2, 7, 10, 13, 14]]

X = pd.concat([credCat, credNum], 1)
y = newCred[15]

scaler = MinMaxScaler()
X_tran = pd.DataFrame(scaler.fit_transform(X))

X_train, X_test, y_train, y_test = train_test_split(X_tran, y, test_size=0.3, random_state=123)

In [97]:
# Base learner
bl1 = RandomForestClassifier(random_state=123)

In [99]:
baggLearner = BaggingClassifier(base_estimator=bl1, n_estimators=10, max_samples=0.8, max_features=0.7)

In [100]:
model = baggLearner.fit(X_train, y_train)

In [101]:
preds = model.predict(X_test)

In [102]:
print(confusion_matrix(y_test, preds))

[[97 10]
 [ 9 80]]


In [103]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.92      0.91      0.91       107
           1       0.89      0.90      0.89        89

    accuracy                           0.90       196
   macro avg       0.90      0.90      0.90       196
weighted avg       0.90      0.90      0.90       196



## Boosting

In [105]:
filename = 'https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter15/Dataset/crx.data '
credData = pd.read_csv(filename, sep= ",", header = None, na_values = "? ")
credData.head()

# O segundo parâmetro fala para modificar apenas a coluna 15
credData.loc[credData[15] == '+', 15] = 1
credData.loc[credData[15] == '-', 15] = 0

credData = credData.replace('?', np.nan)

newCred = credData.dropna(0)

credCat = pd.get_dummies(newCred[[0, 3, 4, 5, 6, 8, 9, 11, 12]])

credNum = newCred[[1, 2, 7, 10, 13, 14]]

X = pd.concat([credCat, credNum], 1)
y = newCred[15]

scaler = MinMaxScaler()
X_tran = pd.DataFrame(scaler.fit_transform(X))

X_train, X_test, y_train, y_test = train_test_split(X_tran, y, test_size=0.3, random_state=123)

In [106]:
bl1 = LogisticRegression(random_state=123)

In [107]:
boosting = AdaBoostClassifier(base_estimator=bl1, n_estimators=200)

In [108]:
model = boosting.fit(X_train, y_train)

In [109]:
preds = model.predict(X_test)

In [110]:
print(confusion_matrix(y_test, preds))

[[96 11]
 [ 8 81]]


In [112]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.92      0.90      0.91       107
           1       0.88      0.91      0.90        89

    accuracy                           0.90       196
   macro avg       0.90      0.90      0.90       196
weighted avg       0.90      0.90      0.90       196



## Stacking

In [113]:
filename = 'https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter15/Dataset/crx.data '
credData = pd.read_csv(filename, sep= ",", header = None, na_values = "? ")
credData.head()

# O segundo parâmetro fala para modificar apenas a coluna 15
credData.loc[credData[15] == '+', 15] = 1
credData.loc[credData[15] == '-', 15] = 0

credData = credData.replace('?', np.nan)

newCred = credData.dropna(0)

credCat = pd.get_dummies(newCred[[0, 3, 4, 5, 6, 8, 9, 11, 12]])

credNum = newCred[[1, 2, 7, 10, 13, 14]]

X = pd.concat([credCat, credNum], 1)
y = newCred[15]

scaler = MinMaxScaler()
X_tran = pd.DataFrame(scaler.fit_transform(X))

X_train, X_test, y_train, y_test = train_test_split(X_tran, y, test_size=0.3, random_state=123)

In [114]:
bl1 = KNeighborsClassifier(n_neighbors=5)
bl2 = RandomForestClassifier(random_state=123)
ml = LogisticRegression(random_state=123)

In [116]:
stackClf = StackingClassifier(classifiers=[bl1, bl2], meta_classifier=ml)

In [117]:
model = stackClf.fit(X_train, y_train)

In [118]:
preds = model.predict(X_test)

In [119]:
print(confusion_matrix(y_test, preds))

[[97 10]
 [ 9 80]]


In [120]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.92      0.91      0.91       107
           1       0.89      0.90      0.89        89

    accuracy                           0.90       196
   macro avg       0.90      0.90      0.90       196
weighted avg       0.90      0.90      0.90       196

